#!/usr/bin/env bash

set -e

RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m' # No Color

if [ 0 -ge $# ]
then
    printf "$RED No argument provided$NC \n"
    exit 2
fi

if [ ! -f $1 ]
then
    printf "$RED File $1 does not exists$NC \n"
    exit 3
fi

out="/tmp/runcpp/$(md5sum $1 | awk '{print $1}')"
mkdir -p $out 2> /dev/null

out="${out}/out"

if [ -e $out ]
then
    printf "${GREEN}File cached $NC \n\n"
else
    g++ -Wall -o "$out" $1
    printf "${GREEN}Out file is $out $NC \n\n"
    chmod +x "$out"
fi

shift
$out $@
