#!/usr/bin/env bash

n_monitors=`hyprctl monitors -j | jq '. | length'`

if (( n_monitors > 1 ))
then
    echo "disable builtin monitor"
    hyprctl keyword monitor "eDP-1, disable"
else
    echo "suspend and lock"
    # swaylock -f --screenshot --effect-blur 10x7
    hyprctl dispatch dpms off
    systemctl suspend
fi
