#!/usr/bin/env bash

n_monitors=`hyprctl monitors -j | jq '. | length'`

if (( n_monitors > 1 ))
then
    # position='1440x1050'
    position='0x1050'
else
    position='0x0'
fi

hyprctl keyword monitor "eDP-1,2736x1824,${position},2"
hyprctl dispatch dpms on
